"""
This is a setup.py script generated by py2applet
+ custom part to move resources to proper location

Usage:
    $ python3 py2applet.py py2app

"""

from setuptools import setup
from datetime import datetime

APP = ['commute.py']
DATA_FILES = ['res/app_muted.png', 'res/app_normal.png', 'res/icon_empty.png', 'res/icon_music.png', 'res/icon_play.png']
OPTIONS = {'iconfile': 'res/ComMute.icns',
           'plist': {'LSUIElement': True,
                     'NSHumanReadableCopyright':'MIT License',
                     'CFBundleName':'ComMute',
                     'CFBundleDisplayName':'ComMute for Spotify',
                     'CFBundleIdentifier':'net.verhey.caspar.commute',
                     'CFBundleVersion': datetime.now().strftime("%Y%m%d"),
                     'CFBundleShortVersionString': datetime.now().strftime("%Y%m%d") }}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)



# put resource files in correct location
import os

APPNAME = OPTIONS['plist']['CFBundleName']
RESPATH = 'dist/'+APPNAME+'.app/Contents/Resources/'

for f in DATA_FILES:
    os.renames(RESPATH+os.path.basename(f), RESPATH+f)

# create DMG
os.system(f'hdiutil create -volname {APPNAME} -srcfolder dist {APPNAME}.dmg')
